spring.application.name=BE_BudgetMate

spring.datasource.url=jdbc:postgresql://localhost:5433/budget-mate-local
spring.datasource.username=root
spring.datasource.password=StrongP@ssword123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000

# Enable compression
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
# Database optimization
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

budgetmate.app.jwtSecret=bnc0dGt5eWVpanVjczlmbGIxd2lzb2ZzOTZmZzl6aXpiOHZwMzN2MGFnYXQxOGo0bmwzd25hYWZzZjZqdmg1ZzNuNDJnNmV0OTUwbnZ1cmVpem94aGNlZzNubzJoMGlybDl1ajZ0bHI1Y21heTd6OXJkYTduMHc0MWFqa3BicnM
#1h
budgetmate.app.jwtExpirationMs=86400000
#1day
budgetmate.app.jwtRefreshExpirationMs=8640000

spring.mail.host=smtp.gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.username=budgetmatecrop@gmail.com

server.port=8080

client.domain=http://localhost:5173/

cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
PAYOS_API_KEY=${PAYOS_API_KEY}
PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}

RETURN_URL=http://localhost:5173/payment-success
CANCEL_URL=http://localhost:5173/payment-failed